feat: update actions + multiarch image

diff --git a/.github/workflows/build-image-fetcher.yml b/.github/workflows/build-image-fetcher.yml
--- a/.github/workflows/build-image-fetcher.yml
+++ b/.github/workflows/build-image-fetcher.yml
@@ -5,72 +5,75 @@ on:
     branches:
       - main
     tags:
-      - '*'
+      - "*"
     paths:
-      - 'Dockerfile_fetcher'
-      - 'src/fetcher/**'
-      - 'requirements-fetcher.txt'
+      - "Dockerfile_fetcher"
+      - "src/fetcher/**"
+      - "requirements-fetcher.txt"
   pull_request:
     paths:
-      - 'Dockerfile_fetcher'
-      - 'src/fetcher/**'
-      - 'requirements-fetcher.txt'
-
+      - "Dockerfile_fetcher"
+      - "src/fetcher/**"
+      - "requirements-fetcher.txt"
 
 jobs:
   docker:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
-    - name: Checkout code
-      uses: actions/checkout@v4
-      with:
-        fetch-depth: 0 
+      - name: Get the latest Git tag
+        id: get_tag
+        run: |
+          TAG=$(git describe --tags --abbrev=0)
+          echo "Latest tag is $TAG"
+          echo "LATEST_TAG=$TAG" >> $GITHUB_ENV
 
-    - name: Get the latest Git tag
-      id: get_tag
-      run: |
-        TAG=$(git describe --tags --abbrev=0)
-        echo "Latest tag is $TAG"
-        echo "LATEST_TAG=$TAG" >> $GITHUB_ENV
-  
-    - name: Set short git commit SHA
-      id: get_sha
-      run: |
-        SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
-        echo "Short commit SHA is $SHORT_SHA"
-        echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
+      - name: Set short git commit SHA
+        id: get_sha
+        run: |
+          SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
+          echo "Short commit SHA is $SHORT_SHA"
+          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
 
-    - name: Confirm git commit SHA and tag variables
-      run: |
-        if [ -z "${{ env.SHORT_SHA }}" ] || [ -z "${{ env.LATEST_TAG }}" ]; then
-          echo "Error: One of SHORT_SHA, LATEST_TAG is empty"
-          exit 1
-        fi
+      - name: Confirm git commit SHA and tag variables
+        run: |
+          if [ -z "${{ env.SHORT_SHA }}" ] || [ -z "${{ env.LATEST_TAG }}" ]; then
+            echo "Error: One of SHORT_SHA, LATEST_TAG is empty"
+            exit 1
+          fi
 
-    # Setup Docker Buildx
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v1
+      # Setup QEMU for multi-arch builds
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
 
-    # Login to Docker Hub
-    - name: Login to DockerHub
-      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
-      uses: docker/login-action@v1
-      with:
-        username: ${{ secrets.DOCKERHUB_USERNAME }}
-        password: ${{ secrets.DOCKERHUB_TOKEN }}
+      # Setup Docker Buildx
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
-    # Build and push fetcher image
-    - name: Build and push fetcher Docker image
-      uses: docker/build-push-action@v2
-      with:
-        context: .
-        file: ./Dockerfile_fetcher
-        push: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')) }}
-        tags: |
-          olegeech/mvcr-application-checker:fetcher-latest
-          olegeech/mvcr-application-checker:fetcher-${{ env.LATEST_TAG }}
-        build-args: |
-          BASE_VERSION=${{ env.LATEST_TAG }}
-          GIT_COMMIT=${{ env.SHORT_SHA }}
+      # Login to Docker Hub
+      - name: Login to DockerHub
+        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      # Build and push fetcher image
+      - name: Build and push fetcher Docker image
+        uses: docker/build-push-action@v6
+        with:
+          context: .
+          file: ./Dockerfile_fetcher
+          platforms: linux/amd64,linux/arm64
+          push: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')) }}
+          tags: |
+            olegeech/mvcr-application-checker:fetcher-latest
+            olegeech/mvcr-application-checker:fetcher-${{ env.LATEST_TAG }}
+          build-args: |
+            BASE_VERSION=${{ env.LATEST_TAG }}
+            GIT_COMMIT=${{ env.SHORT_SHA }}
